name: Amarprotivatv FrontEnd Deployment
on:
  push:
    branches: 'main'
jobs:
  push_event:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd scripts
          ./amar-fe.sh
    - name: google-chat-notification
  # You may pin to the exact commit or the version.
  # uses: Co-qn/google-chat-notification@b9227d9daa4638c9782a5bd16c4abb86268127a1
      uses: Co-qn/google-chat-notification@v1
      with:
        # job name.
        name: Deploy  
        # google chat webhook url.
        url: https://chat.googleapis.com/v1/spaces/AAAAHF1iHEM/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=wCO_dPF1xP0S-rk7GCzkw6EWBdH4B872G63lLVPw1bo%3D
        # job status.
        status: ${{ job.status }}
      if: always()
